config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users

  resources :scripts do
    resources :ratings
  end
  

  get "authors/:id" => "users#show", as: :authors
  post "countview" => "countviews#update", as: :countview

  resources :stars

end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :user
  belongs_to :script
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :script
  belongs_to :user
  validates_presence_of :script, :user
  validate :not_new_user

  Stars = [1,2,3,4,5]

  def not_new_user
    if User.find(self.user_id).created_at > 24.hours.ago
      errors.add(:base, "Sorry, you're account is too new to rate scripts!")
    end
  end
end

app/models/script.rb
class Script < ActiveRecord::Base
  validates_presence_of :slug

  has_many :authors
  has_many :ratings
  has_many :stars

  # http://www.filmsite.org/genres.html
  Genres = %w(action adventure comedy crime drama epic horror musical sci-fi war western)

  def to_param
    # overwrite rails method to return slug for id
    slug
  end

  def set_slug
    slug = title.downcase.gsub(/\W/, "-")
    count = Script.pluck(:slug).select{|s| s == slug }.count
    slug = "#{slug}-#{count}" if count >= 1
    slug
  end

  def count_view
    self.views += 1
    self.save
  end

  def uploaded_by?(user_id)
    self.authors.pluck(:user_id).include? user_id
  end

end

app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :script
  belongs_to :user

  validates_presence_of :user_id, :script_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :email
  has_many :scripts, through: :authors
  has_many :authors
  has_many :ratings
  has_many :stars

  def starred_script?(script_id)
    Star.where(user_id: self.id, script_id: script_id).any?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_paramaters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

  def configure_permitted_paramaters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/countviews_controller.rb
class CountviewsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!

  def update
    @script = Script.find_by_slug(params[:script_slug])
    @script.count_view unless current_user.scripts.include?(@script)
    respond_to do |format|
      format.json { render :nothing => true }
      format.html { render :nothing => true }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    taglines ||= YAML.load_file "lib/assets/taglines.yml"
    @tagline = taglines.to_a.sample
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :authenticate_user!

  def create
    @rating = Rating.create(ratings_params)
    if @rating.save
      flash[:notice] = 'Rating Saved!'
      redirect_to :back
    else
      flash[:alert] = @rating.errors.full_messages.join(' ')
      redirect_to :root
    end
  end

  def update
    @rating = Rating.find(params[:id])
    @rating.update!(ratings_params)
    redirect_to @rating.script, notice: 'Rating updated'
  end

private

  def ratings_params
    params.require(:rating).permit(:script_id, :user_id, :stars)
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!
  before_action :retrieve_script, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    authenticate_script_author(params[:id])
  end


  def index
    @myscripts = Script.where(id: current_user.authors.pluck(:script_id))
    @my_starred_scripts = Script.where(id: current_user.stars.pluck(:script_id)) if current_user
    @scripts = Script.all
  end

  def show
    @rating = Rating.new
    @user_rating = Rating.where(user_id: current_user.id, script_id: @script.id).first
  end

  def create
    @script = CreateScript.with_user(current_user, pdf_params)
    if @script.errors.blank?
      s3o = CreateAwsUpload.with_file(params[:script][:file].original_filename, params[:script][:file].tempfile)
      @script.file_url = s3o.public_url
      @script.pdf_file_name = s3o.key
      redirect_to(@script) if @script.save
    else
      redirect_to(:back, alert: pretty_errors(@script) )
    end
  end

  def new
    @script = Script.new
  end

  def update
    @script.update!(pdf_params)
    redirect_to @script
  end

  def destroy
    @script.destroy
    flash[:notice] = 'Script removed.'
    redirect_to :root
  end

private

  def pdf_params
    params.require(:script).permit(:file, :title, :tagline, :summary, :genre)
  end

  def retrieve_script
    @script = Script.find_by_slug(params[:id])
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController

  def create
    script = Script.find params[:script_id]
    @star = Star.create(user_id: params[:user_id], script_id: script.id)
    redirect_to :back
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def create
    @user = User.create(user_params)
  end

private

  def user_params
    params.require(:email).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(user_params)
  end

  def show
    @user = User.find(params[:id])
  end

private

  def user_params
    params.require(:email).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def authenticate_script_author(script_slug)
    return false unless current_user
    script = current_user.scripts.find_by_slug(script_slug)
    unless current_script_author?(script)
      raise 'Must be current script author.'
    end
  end

  def current_script_author?(script)
    current_user && current_user.scripts.include?(script)
  end

  def pretty_errors(obj)
    obj.errors && obj.errors.full_messages.join('<br>').html_safe
  end
end

app/views/home/index.html.erb
<div class="center">
  <div class='holes'>
    <div class='hole'></div>
    <div class='hole middle-hole'></div>
    <div class='hole'></div>
  </div>

  <h1 class='home-title'>Script Garden</h1>
  <div class='tagline' data-title="<%= @tagline.last %>">
    <p><%= @tagline.first %></p>
  </div>

  <div class='summary'>
    <p class='center'>Script Garden is a place for screenwriters to share their work and get feedback from peers. It's also a place for industry professionals to find the next great script! Grow your skills and your network in the Script Garden.</p>

  </div>
  <div class='signup'>
    <p>Email me to receive an update when we launch.</p>
    <%#= form_for %>
    <strong>mrdougwright on gmail</strong><br>
    <small>app by Doug Wright</small>
  </div>
</div>

app/views/layouts/_nav_menu.html.erb
<ul class='nav_menu'>
  <% if current_user %>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li class='ocg_signup'><%= link_to 'Signup', new_user_registration_path %></li>
    <li><%= link_to 'Login', new_user_session_path %></li>
  <% end %>
  <li><%= link_to 'Scripts', scripts_path %></li>
  <li><%= link_to 'Upload Script', new_script_path %></li>
  <li><%= link_to 'Cover Page', root_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.optimizely.com/js/77413453.js"></script>
  <title>Script Garden</title>
  <%= stylesheet_link_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'https://s3-us-west-2.amazonaws.com/scriptgarden/favicon.ico' %>
</head>
<body>
<nav>
  <%= render 'layouts/nav_menu' %>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<main class="container">
  <%= yield %>
</main>

</body>
</html>

app/views/scripts/_edit_rating_form.html.erb
<div class='form'>
  <%= form_for @user_rating, url: script_rating_path(id: @user_rating.id, script_id: @user_rating.script_id), html: { multipart: true } do |form| %>

    Stars: <%= form.select(:stars, options_for_select(Rating::Stars, @user_rating.stars)) %><br>
    <%= form.submit 'Update Rating', data: { disable_with: "One moment..." } %>
  <% end %>
</div>

app/views/scripts/_new_rating_form.html.erb
<div class='form'>
  <%= form_for [@script, @rating] do |form| %>
    <%= form.hidden_field :script_id, value: @script.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    Stars: <%= form.select(:stars, options_for_select(Rating::Stars)) %><br>
    <%= form.submit 'Save Rating', data: { disable_with: "One moment..." } %>
  <% end %>
</div>

app/views/scripts/_scripts.html.erb
<div class='center'>
  <h2><%= header %></h2>

  <table class="script-table center">
    <thead>
      <th>Title</th>
      <th>Author(s)</th>
      <th>Uploaded On</th>
      <th>Genre</th>
      <th>Views</th>
      <th>Fans</th>
      <th>Ave Rating</th>

    </thead>
    <% scripts.each do |script| %>
      <tbody>
        <tr>
          <td><%= link_to script.title, script %></td>
          <td>
            <% script.authors.each do |author| %>
              <%= link_to author.name, authors_path(id: author.user_id) %>
            <% end %>
          </td>
          <td><%= Format::Date.simple(script.created_at) %></td>
          <td><%= script.genre %></td>
          <td><%= script.views %></td>
          <td><%= Star.where(script_id: script.id).count %></td>
          <td><%= CalculateRatings.ave_rating(script.id) %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/scripts/edit.html.erb
<h1>Edit Script Details</h1>

<div class='form'>
  <%= form_for @script, url: script_path(@script), html: { multipart: true } do |form| %>
    <div class='field'>
      Title: <%= form.text_field :title, required: true %>
    </div>
    <div class='field'>
      Tagline: <%= form.text_field :tagline %>
    </div>
    <div class='field'>
      Summary: <%= form.text_area :summary %>
    </div>
    <div class='actions'>
      <%= form.submit data: { disable_with: "One moment..." } %>
    </div>
  <% end %>
</div>

app/views/scripts/index.html.erb
<h1>Scripts</h1>

<% if @myscripts.blank? %>
  <h3><%= link_to 'Upload a Script!', new_script_path %></h3>
<% else %>
  <%= render 'scripts', scripts: @myscripts, header: 'Uploaded Scripts' %>
<% end %>

<%= render 'scripts', scripts: @my_starred_scripts, header: 'Starred Scripts' unless @my_starred_scripts.blank? %>

<%= render 'scripts', scripts: @scripts, header: 'All Scripts' %>

app/views/scripts/new.html.erb
<div class='form'>
  <%= form_for @script, url: scripts_path, html: { multipart: true } do |form| %>
    <div class='field'>
      Title: <%= form.text_field :title, required: true %>
    </div>
    <div class='field'>
      Tagline: <%= form.text_field :tagline %>
    </div>
    <div class='field'>
      Summary: <%= form.text_area :summary %>
    </div>
    <div class='field'>  
      Genre: <%= form.select(:genre, options_for_select(Script::Genres)) %>
    </div>
    <div class='field'>
      <%= form.file_field :file %>
    </div>
    <div class='actions'>
      <%= form.submit data: { disable_with: "One moment..." } %>
    </div>
  <% end %>
</div>

app/views/scripts/show.html.erb
<h2><%= @script.title %></h2>

<div>
  <p><%= @script.tagline %></p>
  <p><%= @script.summary %></p>
  <p>
    <%= link_to "Read Script", @script.file_url, target: "_blank", onclick: "countView()" %>
  </p>
  <p>
    <%= link_to "Edit Script", edit_script_path(@script) if current_script_author?(@script) %>
  </p>
  <p>
    <%= link_to "Mark as favorite", {
      controller: :stars,
      action: :create,
      user_id: current_user.id,
      script_id: @script.id},
      method: :post unless @script.uploaded_by?(current_user.id) || current_user.starred_script?(@script.id)
    %>
  </p>
  <p><%= link_to "Delete Script", script_path(@script), method: :delete if current_script_author?(@script) %></p>

  <% if @user_rating %>
    <%= render 'edit_rating_form' %>
  <% else %>
    <%= render 'new_rating_form' %>
  <% end %>

</div>

app/views/users/show.html.erb
<%= render 'scripts/scripts', scripts: @user.scripts, header: "#{@user.name}'s Scripts" %>